"""A Clash Verge folder modelled on a real pre-0.5.1 setup (names anonymised): the old generated
Taiwan / Hong Kong groups, AI rule sets that miss part of net.coffee's list, a proxy rule set that
sends some Claude / ChatGPT domains to a Hong Kong exit, and MATCH to Hong Kong as well."""

import pathlib

TW = ["台湾 HiNet 家宽 01 🇨🇳", "台湾 HiNet 家宽 02 🇨🇳", "台湾 HiNet 家宽 03 🇨🇳", "台湾 Seednet 动态家宽 🇹🇼"]
HK = ["香港 家宽 01", "香港 家宽 02", "香港 家宽 03"]
OTHER = ["香港 BGP 01", "🇯🇵 日本 家宽 01", "🇯🇵 日本 02", "🇺🇸 美国 家宽 01", "🇺🇸 美国 01", "🇸🇬 新加坡 01"]
NOTICES = ["剩余流量：312.5 GB", "套餐到期：2026-12-31"]
NODES = TW + HK + OTHER + NOTICES
LATENCY = {name: 90 + 17 * i for i, name in enumerate(NODES)}

PROFILES = """current: RsubE2E001
items:
- uid: RsubE2E001
  type: remote
  name: 订阅
  file: RsubE2E001.yaml
  option:
    update_interval: 1440
    merge: MmergeE2E
    script: SscriptE2E
    rules: RrulesE2E
    proxies: PproxE2E
    groups: GgroupE2E
- uid: RrulesE2E
  type: rules
  file: RrulesE2E.yaml
- uid: GgroupE2E
  type: groups
  file: GgroupE2E.yaml
"""

GROUPS_EXT = """# Generated by scripts/generate-groups.py from config/route-policies.json.
# Do not edit this file directly.

prepend:
  - name: AI 台湾家宽线路
    type: select
    interrupt-exist-connections: false
    proxies:
      - "台湾 HiNet 家宽 01 🇨🇳"
      - "台湾 HiNet 家宽 02 🇨🇳"
      - "台湾 HiNet 家宽 03 🇨🇳"
    disable-udp: true
  - name: SteadyRoute 发现·台湾家宽
    type: select
    include-all-proxies: true
    filter: "(?i)(?:台湾.*家宽)"
    hidden: true
  - name: 香港家宽自动备援
    type: select
    interrupt-exist-connections: false
    proxies:
      - 香港 家宽 01
      - 香港 家宽 02
  - name: SteadyRoute 发现·香港家宽
    type: select
    include-all-proxies: true
    filter: "(?i)(?:香港.*家宽)"
    hidden: true

append: []

delete: []
"""

RULES_EXT = """# Profile Enhancement Rules Template for Clash Verge

prepend: []

append: []

delete: []
"""


def runtime():
    lines = ["mixed-port: 7897", "mode: rule", "ipv6: false", "proxies:"]
    for name in NODES:
        lines += ["- name: %s" % yaml_str(name), "  type: socks5", "  server: 192.0.2.1", "  port: 1080"]
    lines += ["proxy-groups:"]

    def group(name, kind, members=None, extra=()):
        out = ["- name: %s" % yaml_str(name), "  type: %s" % kind]
        out += ["  %s" % item for item in extra]
        if members:
            out += ["  proxies:"] + ["  - %s" % yaml_str(m) for m in members]
        return out
    lines += group("AI 台湾家宽线路", "select", TW[:3], ("interrupt-exist-connections: false", "disable-udp: true"))
    lines += group("SteadyRoute 发现·台湾家宽", "select", None,
                   ("include-all-proxies: true", "filter: '(?i)(?:台湾.*家宽)'", "hidden: true"))
    lines += group("香港家宽自动备援", "select", HK[:2], ("interrupt-exist-connections: false",))
    lines += group("SteadyRoute 发现·香港家宽", "select", None,
                   ("include-all-proxies: true", "filter: '(?i)(?:香港.*家宽)'", "hidden: true"))
    lines += group("🚀 节点选择", "select", ["🇯🇵 日本 家宽 01", "🇯🇵 日本 02", "🇺🇸 美国 家宽 01", "🇺🇸 美国 01", "🇸🇬 新加坡 01"])
    lines += group("家宽出口", "select", ["香港 家宽 03", "香港 BGP 01"])
    lines += group("♻️ 自动选择", "url-test", OTHER, ("url: https://www.gstatic.com/generate_204", "interval: 300"))
    lines += group("🐟 漏网之鱼", "select", ["家宽出口", "🚀 节点选择", "DIRECT"])
    lines += ["rule-providers:",
              "  openai:", "    type: file", "    behavior: classical", "    path: ./ruleset/openai.yaml",
              "  claude:", "    type: file", "    behavior: classical", "    path: ./ruleset/claude.yaml",
              "  proxy:", "    type: file", "    behavior: domain", "    path: ./ruleset/proxy.yaml"]
    lines += ["rules:",
              "- AND,((NETWORK,UDP),(DST-PORT,3478-3481)),REJECT",
              "- RULE-SET,openai,AI 台湾家宽线路",
              "- RULE-SET,claude,AI 台湾家宽线路",
              "- DOMAIN-SUFFIX,google.com,🚀 节点选择",
              "- DOMAIN-SUFFIX,apple.com,DIRECT",
              "- DOMAIN-SUFFIX,netflix.com,🚀 节点选择",
              "- RULE-SET,proxy,家宽出口",
              "- GEOIP,CN,DIRECT",
              "- MATCH,🐟 漏网之鱼"]
    return "\n".join(lines) + "\n"


def yaml_str(value):
    return '"%s"' % value if any(c in value for c in ":#") else value


RULESETS = {
    "openai.yaml": ["DOMAIN-SUFFIX,openai.com", "DOMAIN-SUFFIX,chatgpt.com", "DOMAIN-SUFFIX,oaistatic.com",
                    "DOMAIN-SUFFIX,oaiusercontent.com", "DOMAIN-SUFFIX,sora.com", "DOMAIN-SUFFIX,sentry.io",
                    "DOMAIN-SUFFIX,intercom.io", "DOMAIN-SUFFIX,intercomcdn.com",
                    "DOMAIN-SUFFIX,client-api.arkoselabs.com", "DOMAIN,openai-api.arkoselabs.com",
                    "DOMAIN-SUFFIX,livekit.cloud"],
    "claude.yaml": ["DOMAIN-SUFFIX,anthropic.com", "DOMAIN-SUFFIX,claude.ai", "DOMAIN-SUFFIX,claude.com",
                    "DOMAIN-SUFFIX,claudeusercontent.com", "DOMAIN,anthropic.auth0.com", "DOMAIN,cdn.usefathom.com"],
    "proxy.yaml": ["+.clau.de", "+.claudemcpclient.com", "+.claudemcpcontent.com", "servd-anthropic-website.b-cdn.net",
                   "anthropic.com.cdn.cloudflare.net", "+.chat.com", "+.crixet.com", "+.google.com", "+.github.com"],
}


def build(home):
    home = pathlib.Path(home)
    (home / "profiles").mkdir(parents=True)
    (home / "ruleset").mkdir()
    (home / "profiles.yaml").write_text(PROFILES, encoding="utf-8")
    (home / "profiles" / "GgroupE2E.yaml").write_text(GROUPS_EXT, encoding="utf-8")
    (home / "profiles" / "RrulesE2E.yaml").write_text(RULES_EXT, encoding="utf-8")
    (home / "clash-verge.yaml").write_text(runtime(), encoding="utf-8")
    for name, entries in RULESETS.items():
        (home / "ruleset" / name).write_text("payload:\n" + "".join("  - '%s'\n" % e for e in entries), encoding="utf-8")
    return home
